version: '3'

services:
  petal-homework:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "5000:5000"
