version: 2.1

orbs:
  python: circleci/python@1.2
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest tests
  build-and-push-image:
    steps:
      - aws-ecr/build-and-push-image:
          account-url: ${AWS_ECR_ACCOUNT_URL}
          aws-access-key-id: ${ACCESS_KEY_ID}
          aws-secret-access-key: ${SECRET_ACCESS_KEY}
          checkout: true
          repo: petal-homework
          skip-when-tags-exist: false
          tag: 'latest,prod'

workflows:
  build-and-deploy:
    jobs:
      - run-tests
      - build_and_push_image:
        requires:
          - run-tests
